name: instagram
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # App Icon
  # Splash
  flutter_native_splash: ^2.4.4
  # State Management
  # Navigation
  go_router: ^14.8.1
  # API
  http: ^1.3.0
  # Utilities
  # intl: ^0.18.0
  connectivity_plus: ^4.0.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.1.0
  # flutter_dotenv: ^5.1.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/i_logo.png"
  android_12:
    image: "assets/images/i_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
